'use strict';

angular.module('apidoc', [
        'ngRoute',
        'ui.bootstrap',
        'bbc.transport',
        'bbc.navigation',
        'bbc.session',
        'bbc.alert',
        'bbc.markdown',
        'hljs',
        'pascalprecht.translate',
        'tmh.dynamicLocale'
    ])
    .config(function ($routeProvider, $locationProvider, $bbcNavigationProvider, $translateProvider, $bbcTransportProvider, tmhDynamicLocaleProvider) {

        // Routing and navigation
        $routeProvider
            .when('/apidoc', { templateUrl: 'app/apidoc/apidoc.html' });

        for(var z = 0; z < apiNav.length; z++){
            $routeProvider.when('/apidoc/'+apiNav[z].link+'', { templateUrl: 'app/apidoc/parts/lib/'+apiNav[z].link+'.js.html'})
        }
        // .when('/apidoc/baboon', { templateUrl: 'app/apidoc/parts/lib/baboon.js.html'})
        // .when('/apidoc/config', { templateUrl: 'app/apidoc/parts/lib/config.js.html'})
        // ......
        $routeProvider.otherwise({
                redirectTo: '/apidoc'
            });

        $locationProvider.html5Mode(true);

        $bbcNavigationProvider.set({
            app: 'apidoc',
            route: '/apidoc'
        });

        // Transport
        $bbcTransportProvider.set();

        // Translate
        tmhDynamicLocaleProvider.localeLocationPattern('assets/bower_components/angular-i18n/angular-locale_{{locale}}.js');

        $translateProvider.useStaticFilesLoader({
            prefix: '/locale/guide/locale-',
            suffix: '.json'
        });
        $translateProvider.preferredLanguage('en-us');
        $translateProvider.fallbackLanguage('en-us');
    })
    .run(function ($rootScope, $translate, tmhDynamicLocale, $log, $window, $bbcSession) {

        $rootScope.currentLang = $translate.preferredLanguage();

        $rootScope.switchLocale = function(locale) {
            $translate.use(locale);
            $rootScope.currentLang = locale;
        };

        // flag for needed request by next route change event
        $rootScope.requestNeeded = false;

        // route change event
        $rootScope.$on('$routeChangeStart', function (current, next) {

            // set activity and check session
            $bbcSession.setActivity(function (error) {

                // check session activity error
                if (error) {
                    $log.warn(error);
                    $rootScope.$emit('$sessionInactive');
                }
            });

            // when request needed is true than make a request with next route
            if ($rootScope.requestNeeded) {
                $window.location.assign(next.$$route.originalPath);
            }
        });

        // session inactive event, triggered when session inactive or lost
        $rootScope.$on('$sessionInactive', function() {
            $log.warn('next route change event triggers a server request.');
            $rootScope.requestNeeded = true;
        });

        // translate
        $rootScope.$on('$translateChangeSuccess', function() {
            tmhDynamicLocale.set($translate.use());
        });
    })
    .controller('NavigationCtrl', function ($scope, $location) {

        $scope.menu = apiNav; //api nav is defined in parts/docNavigation.js and autogenerated with grunt doc

    });